FROM kalilinux/kali-linux-docker

# Install necessary dependencies
RUN apt update && apt install -y git
RUN apt upgrade -y

WORKDIR /root

# Clone the repository and run the install script
RUN git clone https://github.com/nahid0x1/0x1nstall.git && \
    cd 0x1nstall && \
    bash install.sh
